# 依赖vici
require File.expand_path(File.dirname(__FILE__) + "/../vici/connection_manager")
require File.expand_path(File.dirname(__FILE__) + "/../vici/generates")

#require File.expand_path(File.dirname(__FILE__) + "/interfaces/interface_helper")
require File.expand_path(File.dirname(__FILE__) + "/helper")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/interface")

#--------------
require File.expand_path(File.dirname(__FILE__) + "/interfaces/character")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/scene")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/action_bar")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/spell")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/container")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/gossip")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/quest")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/party")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/kill")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/loot")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/item")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/gm_command")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/mail")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/mall")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/trade")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/album")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/repair")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/merchant")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/title")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/cron")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/craft")
require File.expand_path(File.dirname(__FILE__) + "/interfaces/error")
