dbconfig = YAML::load(File.new(Conf::DATABASE_CONFIG))
ActiveRecord::Base.establish_connection(dbconfig["development"])

require File.expand_path(File.dirname(__FILE__) + "/models/character")
require File.expand_path(File.dirname(__FILE__) + "/models/account")
require File.expand_path(File.dirname(__FILE__) + "/models/scene")
require File.expand_path(File.dirname(__FILE__) + "/models/portal")
require File.expand_path(File.dirname(__FILE__) + "/models/action_bar")
require File.expand_path(File.dirname(__FILE__) + "/models/container")
require File.expand_path(File.dirname(__FILE__) + "/models/item")
require File.expand_path(File.dirname(__FILE__) + "/models/spell")
require File.expand_path(File.dirname(__FILE__) + "/models/player_quest")
require File.expand_path(File.dirname(__FILE__) + "/models/player_completed_quest")

require File.expand_path(File.dirname(__FILE__) + "/models/party")
require File.expand_path(File.dirname(__FILE__) + "/models/drop")
require File.expand_path(File.dirname(__FILE__) + "/models/gossip")
require File.expand_path(File.dirname(__FILE__) + "/models/party_invite_request")

require File.expand_path(File.dirname(__FILE__) + "/models/scene_object")
require File.expand_path(File.dirname(__FILE__) + "/models/scene_object_item")
require File.expand_path(File.dirname(__FILE__) + "/models/scene_npc")
require File.expand_path(File.dirname(__FILE__) + "/models/loot")
require File.expand_path(File.dirname(__FILE__) + "/models/loot_roll")
require File.expand_path(File.dirname(__FILE__) + "/models/open_loot")

require File.expand_path(File.dirname(__FILE__) + "/models/mail")
require File.expand_path(File.dirname(__FILE__) + "/models/mail_attachment")
require File.expand_path(File.dirname(__FILE__) + "/models/mall")
require File.expand_path(File.dirname(__FILE__) + "/models/trade")
require File.expand_path(File.dirname(__FILE__) + "/models/trade_item")
require File.expand_path(File.dirname(__FILE__) + "/models/album")
require File.expand_path(File.dirname(__FILE__) + "/models/title")
require File.expand_path(File.dirname(__FILE__) + "/models/craft")
require File.expand_path(File.dirname(__FILE__) + "/models/recipe")
require File.expand_path(File.dirname(__FILE__) + "/models/zone")
require File.expand_path(File.dirname(__FILE__) + "/models/merchant")
require File.expand_path(File.dirname(__FILE__) + "/models/error")
