module QuestDataHelper
  def prepare_static_quests
    @quest_1 = {"reward6_is_option"=>nil, "reward6"=>nil, "objective4_npc"=>nil, "completeaction_params"=>"", "prev_quest"=>nil, "name"=>"test对话", "reward3_amount"=>nil, "objective4_item"=>nil, "objective3_gossip"=>nil, "objective3_type"=>nil, "objective1_amount"=>1, "reward2_is_option"=>nil, "repeat_daily"=>nil, "gain_money"=>100, "reward3_is_option"=>nil, "objective2_type"=>nil, "objective1_gossip"=>80, "start_npc"=>12, "level"=>1, "type"=>1, "objective2_npc"=>nil, "objective1_type"=>3, "id"=>3, "gain_xp"=>100, "reward5_is_option"=>nil, "reward5_amount"=>nil, "reward1_is_option"=>nil, "reward1"=>nil, "objective3_npc"=>nil, "objective3_item"=>nil, "progress"=>"赶紧着！", "description"=>"去找10说话", "complete_action"=>nil, "accept_action_params"=>"", "accept_action"=>nil, "reward4_amount"=>nil, "reward2"=>nil, "objective3_amount"=>nil, "objective2_item"=>nil, "objective"=>"和10对话", "end_npc"=>11, "reward3"=>nil, "objective4_gossip"=>nil, "objective4_type"=>nil, "objective2_amount"=>nil, "objective1_npc"=>10, "objective1_item"=>nil, "reward6_amount"=>nil, "reward4_is_option"=>nil, "reward4"=>nil, "reward2_amount"=>nil, "reward5"=>nil, "reward1_amount"=>nil, "objective4_amount"=>nil, "objective2_gossip"=>nil, "completion"=>"了解了。", "profession"=>nil}
    
    @quest_2 = {"reward6_is_option"=>nil, "reward6"=>nil, "objective4_npc"=>nil, "completeaction_params"=>"", "prev_quest"=>nil, "name"=>"test收集", "reward3_amount"=>nil, "objective4_item"=>nil, "objective3_gossip"=>nil, "objective3_type"=>nil, "objective1_amount"=>1, "reward2_is_option"=>nil, "repeat_daily"=>nil, "gain_money"=>20, "reward3_is_option"=>nil, "objective2_type"=>nil, "objective1_gossip"=>nil, "start_npc"=>11, "level"=>1, "type"=>1, "objective2_npc"=>nil, "objective1_type"=>2, "id"=>2, "gain_xp"=>200, "reward5_is_option"=>nil, "reward5_amount"=>nil, "reward1_is_option"=>nil, "reward1"=>nil, "objective3_npc"=>nil, "objective3_item"=>nil, "progress"=>"熊王的头颅呢？", "description"=>"那些该死的熊是由一只熊王率领的，给我收集4个血瓶，我会给你报酬的。", "complete_action"=>nil, "accept_action_params"=>"", "accept_action"=>nil, "reward4_amount"=>nil, "reward2"=>nil, "objective3_amount"=>nil, "objective2_item"=>nil, "objective"=>"收集4个血瓶", "end_npc"=>12, "reward3"=>nil, "objective4_gossip"=>nil, "objective4_type"=>nil, "objective2_amount"=>nil, "objective1_npc"=>nil, "objective1_item"=>121002, "reward6_amount"=>nil, "reward4_is_option"=>nil, "reward4"=>nil, "reward2_amount"=>nil, "reward5"=>nil, "reward1_amount"=>nil, "objective4_amount"=>nil, "objective2_gossip"=>nil, "completion"=>"太好了，我又能养羊了！", "profession"=>nil}

    @quest_3 = {"reward6_is_option"=>nil, "reward6"=>nil, "objective4_npc"=>nil, "completeaction_params"=>"", "prev_quest"=>nil, "name"=>"test收集", "reward3_amount"=>nil, "objective4_item"=>nil, "objective3_gossip"=>nil, "objective3_type"=>nil, "objective1_amount"=>1, "reward2_is_option"=>nil, "repeat_daily"=>nil, "gain_money"=>20, "reward3_is_option"=>nil, "objective2_type"=>nil, "objective1_gossip"=>nil, "start_npc"=>11, "level"=>1, "type"=>1, "objective2_npc"=>nil, "objective1_type"=>2, "id"=>2, "gain_xp"=>200, "reward5_is_option"=>nil, "reward5_amount"=>nil, "reward1_is_option"=>nil, "reward1"=>nil, "objective3_npc"=>nil, "objective3_item"=>nil, "progress"=>"熊王的头颅呢？", "description"=>"那些该死的熊是由一只熊王率领的，给我收集4个血瓶，我会给你报酬的。", "complete_action"=>nil, "accept_action_params"=>"", "accept_action"=>nil, "reward4_amount"=>nil, "reward2"=>nil, "objective3_amount"=>nil, "objective2_item"=>nil, "objective"=>"收集4个血瓶", "end_npc"=>12, "reward3"=>nil, "objective4_gossip"=>nil, "objective4_type"=>nil, "objective2_amount"=>nil, "objective1_npc"=>nil, "objective1_item"=>121002, "reward6_amount"=>nil, "reward4_is_option"=>nil, "reward4"=>nil, "reward2_amount"=>nil, "reward5"=>nil, "reward1_amount"=>nil, "objective4_amount"=>nil, "objective2_gossip"=>nil, "completion"=>"太好了，我又能养羊了！", "profession"=>nil}

    @quest_4 = {"reward6_is_option"=>nil, "reward6"=>nil, "objective4_npc"=>nil, "completeaction_params"=>"", "prev_quest"=>nil, "name"=>"打怪+传送", "reward3_amount"=>1, "objective4_item"=>nil, "objective3_gossip"=>nil, "objective3_type"=>nil, "objective1_amount"=>1, "reward2_is_option"=>1, "repeat_daily"=>nil, "gain_money"=>10, "reward3_is_option"=>1, "objective2_type"=>nil, "objective1_gossip"=>nil, "start_npc"=>10, "level"=>1, "type"=>1, "objective2_npc"=>nil, "objective1_type"=>1, "id"=>5, "gain_xp"=>150, "reward5_is_option"=>nil, "reward5_amount"=>nil, "reward1_is_option"=>1, "reward1"=>70, "objective3_npc"=>nil, "objective3_item"=>nil, "progress"=>"熊杀好了？", "description"=>"接受这个任务，你将被传送到另外一个场景里", "complete_action"=>nil, "accept_action_params"=>"122.0", "accept_action"=>400, "reward4_amount"=>1, "reward2"=>80, "objective3_amount"=>nil, "objective2_item"=>nil, "objective"=>"", "end_npc"=>13, "reward3"=>81, "objective4_gossip"=>nil, "objective4_type"=>nil, "objective2_amount"=>nil, "objective1_npc"=>101001, "objective1_item"=>nil, "reward6_amount"=>nil, "reward4_is_option"=>1, "reward4"=>84, "reward2_amount"=>1, "reward5"=>nil, "reward1_amount"=>5, "objective4_amount"=>nil, "objective2_gossip"=>nil, "completion"=>"英雄！你太牛了！", "profession"=>nil}

  end

end
